using System.Globalization;
using System.Text;
using System.Xml.Linq;
using UiSharp.Core.Actions;
using UiSharp.Core.Actions.Impl;
using UiSharp.Core.Configuration;
using UiSharp.Core.Dialogs;
using UiSharp.Core.Logging;
using UiSharp.Core.Scripting;
using UiSharp.Core.Software;
using UiSharp.Core.Variables;

namespace UiSharp.Core.Tests.Parity;

/// <summary>
/// Renders a real configuration file into a deterministic text snapshot.
///
/// What this DOES cover: XML parsing, the resolved global dialog traits, the
/// software catalog, the order in which the action processor visits actions, every
/// condition it evaluates (including diagnostics), the input-field and preflight
/// specs the Core parsers produce, and the variable flow through the pure actions.
///
/// What this does NOT cover: real dialogs, WMI, the registry, the network, or
/// external DLLs. Those actions are recorded from their XML and skipped, so the
/// snapshot pins configuration *resolution*, not runtime behaviour.
/// </summary>
internal sealed class ConfigParityRecorder
{
    // Action types executed for real: pure logic, no I/O, deterministic.
    private static readonly string[] ExecutedForReal =
    [
        XmlConstants.ActionTypes.TSVar,
        XmlConstants.ActionTypes.Switch,
        XmlConstants.ActionTypes.TSVarList,
    ];

    // Dialog action types — recorded, but flagged as GUI actions so the
    // processor's Back/Refresh bookkeeping behaves as it would at runtime.
    private static readonly HashSet<string> GuiActionTypes =
        new(StringComparer.OrdinalIgnoreCase)
        {
            XmlConstants.ActionTypes.UserInput,
            XmlConstants.ActionTypes.UserInfo,
            XmlConstants.ActionTypes.UserInfoFull,
            XmlConstants.ActionTypes.ErrorInfo,
            XmlConstants.ActionTypes.AppTree,
            XmlConstants.ActionTypes.UserAuth,
            XmlConstants.ActionTypes.Preflight,
        };

    // A fixed stand-in for the process environment. Without this, a config
    // referencing %ComputerName% would bake the host machine's name into the
    // snapshot. Anything not listed stays as a literal %Token%, which is what the
    // original C++ does for an unset variable.
    private static readonly Dictionary<string, string> FakeEnvironment =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["ComputerName"] = "PARITY-TEST-PC",
        };

    // A fixed stand-in for the machine. CreateObject("Scripting.FileSystemObject")
    // is now evaluated natively, so without this a snapshot would depend on which
    // files happen to exist on the machine running the tests.
    private sealed class FixedScriptHost : IScriptHostServices
    {
        public bool FileExists(string path)   => false;
        public bool FolderExists(string path) => false;
        public bool DriveExists(string drive) => drive.StartsWith("C", StringComparison.OrdinalIgnoreCase);

        public string ComputerName => "PARITY-TEST-PC";
        public string UserName     => "parityuser";
        public string UserDomain   => "PARITYDOMAIN";

        public string ExpandEnvironmentStrings(string input) => input;
    }

    private static readonly FixedScriptHost ScriptHost = new();

    private static NativeConditionEvaluator NewEvaluator() => new(ScriptHost);

    private readonly List<string> _actionLines = [];
    private readonly CapturingLog _log = new();
    private readonly LocalTSEnv _env =
        new(name => FakeEnvironment.TryGetValue(name, out var v) ? v : null);

    private int _actionIndex;

    // -------------------------------------------------------------------------

    public static string Record(string fileName)
    {
        var config = ConfigLoader.Load(SampleConfigs.PathFor(fileName));
        return new ConfigParityRecorder().Build(fileName, config);
    }

    private string Build(string fileName, LoadedConfig config)
    {
        var sb = new StringBuilder();

        Header(sb, fileName);
        ConfigSection(sb, config);
        SoftwareSection(sb, config);
        RunActions(config);
        ActionSection(sb);
        VariableSection(sb);
        LogSection(sb);

        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Report sections
    // -------------------------------------------------------------------------

    private static void Header(StringBuilder sb, string fileName)
    {
        sb.AppendLine($"# Parity snapshot — {fileName}");
        sb.AppendLine();
        sb.AppendLine("Generated by ConfigParityRecorder. Covers configuration resolution only:");
        sb.AppendLine("dialogs, WMI, the registry, the network and external DLLs are recorded and");
        sb.AppendLine("skipped rather than executed. Regenerate with UISHARP_UPDATE_GOLDEN=1.");
        sb.AppendLine();
    }

    private static void ConfigSection(StringBuilder sb, LoadedConfig config)
    {
        var t = config.GlobalTraits;

        sb.AppendLine("## Global dialog traits");
        sb.AppendLine();
        Field(sb, "Title",            Quote(t.Title));
        Field(sb, "Subtitle",         Quote(t.Subtitle));
        Field(sb, "FontFace",         Quote(t.FontFace));
        Field(sb, "IconPath",         t.IconPath is null ? "(none)" : Quote(t.IconPath));
        Field(sb, "AccentColor",      Hex(t.AccentColor));
        Field(sb, "TextColor",        Hex(t.TextColor));
        Field(sb, "SidebarTextColor", Hex(t.SidebarTextColor));
        Field(sb, "ScreenScaleX",     t.ScreenScaleX.ToString("0.###", CultureInfo.InvariantCulture));
        Field(sb, "ScreenScaleY",     t.ScreenScaleY.ToString("0.###", CultureInfo.InvariantCulture));
        Field(sb, "Flags",            DescribeFlags(t.Flags));
        sb.AppendLine();

        sb.AppendLine("## Config");
        sb.AppendLine();
        Field(sb, "ConditionEngine", config.ConditionEngine);
        Field(sb, "SchemaVersion",   config.SchemaVersion?.ToString(CultureInfo.InvariantCulture) ?? "(none)");
        Field(sb, "Messages",        config.Messages is null ? "(none)" : "(present)");
        sb.AppendLine();
    }

    private static void SoftwareSection(StringBuilder sb, LoadedConfig config)
    {
        sb.AppendLine($"## Software catalog ({config.Software.Count})");
        sb.AppendLine();

        if (config.Software.Count == 0)
        {
            sb.AppendLine("(empty)");
            sb.AppendLine();
            return;
        }

        // Ordered by the OrderIndex the parser assigned, then Id, so the snapshot
        // does not depend on dictionary enumeration order.
        foreach (var sw in config.Software.Values
                     .OrderBy(s => s.OrderIndex)
                     .ThenBy(s => s.Id, StringComparer.Ordinal))
        {
            sb.AppendLine($"- [{sw.OrderIndex}] {sw.Type} Id={Quote(sw.Id)} Label={Quote(sw.Label)}");
            if (!string.IsNullOrEmpty(sw.Info))       sb.AppendLine($"    Info={Quote(sw.Info)}");
            if (!string.IsNullOrEmpty(sw.IncludeIds)) sb.AppendLine($"    IncludeIds={Quote(sw.IncludeIds)}");
            if (!string.IsNullOrEmpty(sw.ExcludeIds)) sb.AppendLine($"    ExcludeIds={Quote(sw.ExcludeIds)}");
            sb.AppendLine($"    VariableValue={Quote(sw.GetVariableValue())}");
        }
        sb.AppendLine();
    }

    private void ActionSection(StringBuilder sb)
    {
        sb.AppendLine($"## Action sequence ({_actionIndex} executed)");
        sb.AppendLine();

        if (_actionLines.Count == 0)
            sb.AppendLine("(no actions ran)");
        else
            foreach (var line in _actionLines) sb.AppendLine(line);

        sb.AppendLine();
    }

    private void VariableSection(StringBuilder sb)
    {
        var vars = _env.GetAll()
            .OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase)
            .ToList();

        sb.AppendLine($"## Task-sequence variables after the run ({vars.Count})");
        sb.AppendLine();

        if (vars.Count == 0)
            sb.AppendLine("(none set)");
        else
            foreach (var (k, v) in vars) sb.AppendLine($"{k} = {Quote(v)}");

        sb.AppendLine();
    }

    private void LogSection(StringBuilder sb)
    {
        var notable = _log.Entries
            .Where(e => e.Severity != LogSeverity.Info)
            .Select(e => $"[{e.Severity}] {e.Message}")
            .ToList();

        sb.AppendLine($"## Warnings and errors ({notable.Count})");
        sb.AppendLine();

        if (notable.Count == 0)
            sb.AppendLine("(none)");
        else
            foreach (var line in notable) sb.AppendLine(line);
    }

    // -------------------------------------------------------------------------
    // Running the action graph
    // -------------------------------------------------------------------------

    private void RunActions(LoadedConfig config)
    {
        var actionsEl = config.Document.Root?.Element(XmlConstants.Elements.Actions);
        if (actionsEl is null)
        {
            _actionLines.Add("(config has no <Actions> element)");
            return;
        }

        var real = new ActionFactory();
        real.RegisterFromAssembly(typeof(ActionTSVar).Assembly);

        var factory = BuildRecordingFactory(real);

        var data = new ActionData
        {
            ActionNode         = actionsEl,
            Conditions         = NewEvaluator(),
            TsEnv              = _env,
            Log                = _log,
            GlobalDialogTraits = config.GlobalTraits,
            Software           = config.Software,
            Messages           = config.Messages,
        };

        var result = new ActionProcessor(factory, NewEvaluator())
            .Run(actionsEl, data);

        _actionLines.Add($"=> processor result: {result}");
    }

    private ActionFactory BuildRecordingFactory(ActionFactory real)
    {
        var factory = new ActionFactory();

        // Every action type known to the schema gets a recording stub, so a type
        // this port fails to handle shows up in the snapshot rather than vanishing.
        foreach (var typeName in AllKnownActionTypes())
        {
            var captured = typeName;
            factory.Register(captured, data => new RecordingAction(
                record: () => _actionLines.AddRange(Describe(captured, data)),
                isGuiAction: GuiActionTypes.Contains(captured)));
        }

        // Pure actions run for real, wrapped so they still appear in the sequence.
        foreach (var typeName in ExecutedForReal)
        {
            var captured = typeName;
            factory.Register(captured, data =>
            {
                var inner = real.Create(captured, data)
                    ?? throw new InvalidOperationException(
                        $"Core does not implement '{captured}', but it is listed as executed for real.");

                return new RecordingAction(
                    record: () => _actionLines.AddRange(Describe(captured, data)),
                    isGuiAction: false,
                    inner: inner);
            });
        }

        return factory;
    }

    // Reflects over XmlConstants.ActionTypes so a new action type cannot be
    // silently omitted from the recorder.
    private static IEnumerable<string> AllKnownActionTypes() =>
        typeof(XmlConstants.ActionTypes)
            .GetFields(System.Reflection.BindingFlags.Public |
                       System.Reflection.BindingFlags.Static |
                       System.Reflection.BindingFlags.FlattenHierarchy)
            .Where(f => f.IsLiteral && f.FieldType == typeof(string))
            .Select(f => (string)f.GetRawConstantValue()!);

    private sealed class RecordingAction(
        Action record,
        bool isGuiAction,
        IAction? inner = null) : IAction
    {
        public bool IsGuiAction => isGuiAction;

        public ActionResult Go()
        {
            // Record before running, so the snapshot shows the variable values the
            // action actually saw rather than the ones it went on to write.
            record();
            return inner?.Go() ?? ActionResult.Next;
        }
    }

    // -------------------------------------------------------------------------
    // Per-action descriptions
    // -------------------------------------------------------------------------

    private IEnumerable<string> Describe(string typeName, ActionData data)
    {
        var node = data.ActionNode;
        var lines = new List<string>();

        _actionIndex++;
        var header = $"[{_actionIndex:D2}] {typeName}";

        var name = (string?)node.Attribute(XmlConstants.Attributes.Name);
        if (!string.IsNullOrEmpty(name)) header += $" Name={Quote(name)}";

        var title = (string?)node.Attribute(XmlConstants.Attributes.Title);
        if (!string.IsNullOrEmpty(title)) header += $" Title={Quote(data.TsEnv.Substitute(title))}";

        var condition = (string?)node.Attribute(XmlConstants.Attributes.Condition);
        if (!string.IsNullOrEmpty(condition)) header += "  [conditional]";

        lines.Add(header);

        // Attributes other than the ones already in the header.
        var shown = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            { XmlConstants.Attributes.Type, XmlConstants.Attributes.Name, XmlConstants.Attributes.Title };

        var attrs = node.Attributes()
            .Where(a => !shown.Contains(a.Name.LocalName))
            .OrderBy(a => a.Name.LocalName, StringComparer.Ordinal)
            .Select(a => $"{a.Name.LocalName}={Quote(a.Value)}")
            .ToList();

        if (attrs.Count > 0)
            lines.Add($"     attrs: {string.Join(" ", attrs)}");

        lines.AddRange(DescribeBody(typeName, data));
        return lines;
    }

    private IEnumerable<string> DescribeBody(string typeName, ActionData data)
    {
        if (typeName.Equals(XmlConstants.ActionTypes.UserInput, StringComparison.OrdinalIgnoreCase))
            return DescribeInput(data);

        if (typeName.Equals(XmlConstants.ActionTypes.Preflight, StringComparison.OrdinalIgnoreCase))
            return DescribePreflight(data);

        return DescribeGenericBody(data);
    }

    // Exercises the real InputFieldParser against a real config, then applies each
    // field's default value — the state a dialog would start in, and what the rest
    // of the config sees if the operator just presses Next.
    private IEnumerable<string> DescribeInput(ActionData data)
    {
        var specs = InputFieldParser.Parse(data.ActionNode, data.TsEnv, data.Conditions, data.Log);
        var lines = new List<string> { $"     fields: {specs.Count}" };

        foreach (var spec in specs)
        {
            switch (spec)
            {
                case InputTextSpec text:
                    lines.Add($"       - Text     Variable={Quote(text.Variable)} Question={Quote(text.Question)}");
                    lines.Add($"                  Default={Quote(text.DefaultValue)} Required={text.Required} Password={text.Password}");
                    if (!string.IsNullOrEmpty(text.Prompt))     lines.Add($"                  Prompt={Quote(text.Prompt)}");
                    if (!string.IsNullOrEmpty(text.Hint))       lines.Add($"                  Hint={Quote(text.Hint)}");
                    if (!string.IsNullOrEmpty(text.Regex))      lines.Add($"                  Regex={Quote(text.Regex)}");
                    if (!string.IsNullOrEmpty(text.ForceCase))  lines.Add($"                  ForceCase={Quote(text.ForceCase)}");
                    if (!string.IsNullOrEmpty(text.AdValidate)) lines.Add($"                  AdValidate={Quote(text.AdValidate)}");
                    if (text.ReadOnly)                          lines.Add("                  ReadOnly=True");
                    if (text.HorizontalScroll)                  lines.Add("                  HorizontalScroll=True");
                    data.TsEnv.Set(text.Variable, text.DefaultValue);
                    break;

                case InputChoiceSpec choice:
                    lines.Add($"       - Choice   Variable={Quote(choice.Variable)} Question={Quote(choice.Question)}");
                    lines.Add($"                  Default={Quote(choice.DefaultValue)} Required={choice.Required} " +
                              $"Sort={choice.Sort} AutoComplete={choice.AutoComplete} DropDownSize={choice.DropDownSize}");
                    if (!string.IsNullOrEmpty(choice.AltVariable))
                        lines.Add($"                  AltVariable={Quote(choice.AltVariable)}");
                    lines.Add($"                  choices: {choice.Choices.Count}");
                    foreach (var c in choice.Choices)
                        lines.Add($"                    * Option={Quote(c.Option)} Value={Quote(c.Value)} Alt={Quote(c.AltValue)}");
                    data.TsEnv.Set(choice.Variable, choice.DefaultValue);
                    break;

                case InputCheckboxSpec cb:
                    lines.Add($"       - Checkbox Variable={Quote(cb.Variable)} Question={Quote(cb.Question)}");
                    lines.Add($"                  Default={Quote(cb.DefaultValue)} Checked={Quote(cb.CheckedValue)} " +
                              $"Unchecked={Quote(cb.UncheckedValue)}");
                    data.TsEnv.Set(cb.Variable, cb.DefaultValue);
                    break;

                case InputInfoSpec info:
                    lines.Add($"       - Info     Text={Quote(info.Question)}");
                    lines.Add($"                  TextColor={Quote(info.TextColor)} NumberOfLines={info.NumberOfLines}");
                    break;

                default:
                    lines.Add($"       - {spec.GetType().Name} Question={Quote(spec.Question)}");
                    break;
            }
        }

        return lines;
    }

    // Exercises the real PreflightEvaluator. Checks referencing hardware facts
    // fail here because DefaultValues never ran — the point is that the checks
    // parse and evaluate consistently, not that this machine passes them.
    private IEnumerable<string> DescribePreflight(ActionData data)
    {
        var checks  = PreflightEvaluator.ParseChecks(data.ActionNode, data.TsEnv, data.Conditions, data.Log);
        var results = PreflightEvaluator.Evaluate(checks, data.Conditions, data.TsEnv, data.Log);

        var lines = new List<string> { $"     checks: {checks.Count}" };

        foreach (var r in results)
        {
            lines.Add($"       - [{r.Status}] {Quote(r.Check.Text)}");
            if (!string.IsNullOrEmpty(r.Check.CheckCondition))
                lines.Add($"                  CheckCondition={Quote(r.Check.CheckCondition)}");
            if (!string.IsNullOrEmpty(r.Check.WarnCondition))
                lines.Add($"                  WarnCondition={Quote(r.Check.WarnCondition)}");
            if (!string.IsNullOrEmpty(r.ActiveDescription))
                lines.Add($"                  ActiveDescription={Quote(r.ActiveDescription)}");
        }

        lines.Add($"     any failed: {PreflightEvaluator.AnyFailed(results)}");
        return lines;
    }

    // Structure dump for actions this recorder does not execute: child elements
    // and inner text, so the config's shape is still pinned.
    private static IEnumerable<string> DescribeGenericBody(ActionData data)
    {
        var lines = new List<string>();
        var node  = data.ActionNode;

        var text = string.Concat(node.Nodes().OfType<XText>().Select(n => n.Value)).Trim();
        if (!string.IsNullOrEmpty(text))
            lines.Add($"     text: {Quote(text)}");

        foreach (var child in node.Elements())
            lines.AddRange(DescribeElement(child, depth: 1));

        return lines;
    }

    private static IEnumerable<string> DescribeElement(XElement el, int depth)
    {
        var indent = new string(' ', 5 + depth * 2);
        var attrs = el.Attributes()
            .OrderBy(a => a.Name.LocalName, StringComparer.Ordinal)
            .Select(a => $"{a.Name.LocalName}={Quote(a.Value)}");

        var line = $"{indent}<{el.Name.LocalName}> {string.Join(" ", attrs)}".TrimEnd();
        yield return line;

        var text = string.Concat(el.Nodes().OfType<XText>().Select(n => n.Value)).Trim();
        if (!string.IsNullOrEmpty(text))
            yield return $"{indent}  text: {Quote(text)}";

        foreach (var child in el.Elements())
            foreach (var childLine in DescribeElement(child, depth + 1))
                yield return childLine;
    }

    // -------------------------------------------------------------------------
    // Formatting helpers
    // -------------------------------------------------------------------------

    private static void Field(StringBuilder sb, string name, string value) =>
        sb.AppendLine($"{name,-17}: {value}");

    // Collapses newlines and tabs so every recorded value stays on one line, and
    // makes leading/trailing whitespace visible in a diff.
    private static string Quote(string? value)
    {
        if (value is null) return "(null)";
        var flat = value
            .Replace("\r\n", "\\n")
            .Replace("\r", "\\n")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
        return $"\"{flat}\"";
    }

    private static string Hex(System.Drawing.Color c) =>
        $"#{c.R:X2}{c.G:X2}{c.B:X2}";

    // Renders flags in a fixed declaration order rather than relying on
    // Enum.ToString, whose ordering is not part of its contract.
    private static string DescribeFlags(DialogTraitFlags flags)
    {
        DialogTraitFlags[] order =
        [
            DialogTraitFlags.ShowIcons,
            DialogTraitFlags.ShowSidebar,
            DialogTraitFlags.AllowVarEditor,
            DialogTraitFlags.AllowBack,
            DialogTraitFlags.AllowRefresh,
            DialogTraitFlags.Flat,
            DialogTraitFlags.AlwaysOnTop,
        ];

        var set = order.Where(f => flags.HasFlag(f)).Select(f => f.ToString()).ToList();
        return set.Count == 0 ? "None" : string.Join(" | ", set);
    }

    // -------------------------------------------------------------------------

    private sealed class CapturingLog : ICMLog
    {
        public List<(LogSeverity Severity, string Message)> Entries { get; } = [];

        public void Write(string msg, LogSeverity sev = LogSeverity.Info, string comp = LogFile.DefaultComponent) =>
            Entries.Add((sev, msg));
    }
}
