<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UiSharp.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.0" />
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UiSharp.Core\UiSharp.Core.csproj" />
  </ItemGroup>

</Project>
